# Generated by Django 3.2.9 on 2021-11-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rate'),
        ('movies', '0002_rating'),
    ]

    operations = [
    ]
