# Generated by Django 3.2.9 on 2021-11-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20211121_2036'),
        ('community', '0003_auto_20211120_2249'),
    ]

    operations = [
    ]
