# Generated by Django 3.2.9 on 2021-11-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_merge_0002_auto_20211121_2036_0003_auto_20211120_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5),
        ),
    ]
