# Generated by Django 3.2.9 on 2021-11-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rate_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
